kind: Deployment
apiVersion: apps/v1
metadata:
  name: container
  namespace: purplecallui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
        - name: container
          image: emn503/loginapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: container-service
  namespace: purplecallui
spec:
  selector:
    app: container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
